### ISSUE TITLE
Cannot authorize app access to redmine account

### ISSUE THREAD

**Issue by naxim92** [Virtualmaster/redmine-oauth-provider#1]
I deployed redmine+oauth+another site, which need oauth authentication through redmine.
When I try to go to my site I get
1. redmine auth window (I login here)
2. redmine page with text:

> Authorize access to your account
>
>Would you like to authorize test elastic (http://oauth.***.ru) to access your account?

and nothing else. I expect here are 2 buttons "Authorize" and "Deny" and a list of data which will be able to oauth_provider or something like this. But I don't see anything else.

`<p>Would you like to authorize <a href="http://oauth.***.ru">test elastic</a> (<a href="http://oauth.***.ru">http://oauth.***.ru</a>) to access your account?</p>`

**Comment by phokz** [comment]
Hi, we are not using redmine anymore and this repo stays here mostly as an historic artefact. As you can see it has not been touched for 7 years.

Use another, I'd try https://github.com/suer/redmine_oauth_provider
Maybe also read this http://www.redmine.org/issues/24808 to see what the status.

If none of the alternatives suits your need, feel free to fork this or you can take over maintenance of this.

**Comment by naxim92** [comment]
It seems we use not this one but plugin from suer. My mistake.
